<?php

return [

    'title' => 'FELTÉTELEK ÉS FELTÉTELEK INGYENES DÍJONHOZ, A „ŠÍRAVA PARK 2-S SZÁLLÍTÁSA”',
    'cond' => 'A belépés feltételei',
    '1' => '1. Ez a nyereményjáték (a "Promóció") csak az EU lakosai számára nyitva áll, kivéve a (a) A promóció alkalmazottjait és ügynökeit, vagy (b) bármely, a promóció előállításával vagy forgalmazásával kapcsolatos társaságot, valamint a hozzátartozóik vagy a hozzátartozóik tagjait. családjuk vagy háztartásuk.',
    '2' => '2. A pályázóknak 18 éves vagy annál idősebbnek kell lenniük a belépéskor. A jogosultság igazolását kérésre kell benyújtani. A promócióba való belépéskor úgy kell tekinteni, hogy elfogadja és köti ezeket a feltételeket.',
    '3' => '3. A promóció 2018. november 8-án, csütörtökön 11:00 órakor kezdődik, és a promóció záró időpontja / dátuma: 20:00 GMT 2020. november 8-án (promóciós időszak).',
    '4' => '4. Egy győztes lesz, akit egy független bíró véletlenszerűen választ ki a hónap első napján, minden hónapban, 2019 márciusától 2020 novemberéig tartott minden jogosult bejegyzésből. A nyertes (ek) a hirdető e-mailben, vagy a közösségi médián keresztül történő közvetlen üzenetküldés útján értesíti. ebből a dátumból egy héttel, és részleteket kapnak arról, hogyan fogadják el a díjat. Ha a nyertes (ek) nem fogadják el a nyereményt a promóter e-mailétől számított egy héten belül, akkor minden követelés érvénytelenné válik, és a promóter ezután egy másik nyertest választ ki (ismételten véletlenszerűen kiválasztva) a többi jogosult bejegyzések, amelyekkel a fentiekben felveszi a kapcsolatot.',
    '5' => '5. A pályázók egyetértenek abban, hogy ésszerű együttműködést tesznek lehetővé annak érdekében, hogy a pályázó a promócióhoz kapcsolódóan a nyertes nevét és / vagy hasonlóságát reklámozási és reklámozási célokra felhasználhassa, beleértve a nyertes nevének és fényképének közzétételét a promóciós weboldalakon . Továbbá, a bejegyzés benyújtásával és a promóciónak a promócióba való belépésének jogát figyelembe véve a résztvevők megállapodnak abban, hogy a Promóternek örökös, jogdíjmentes, nem kizárólagos, engedéllyel rendelkező jogot és licencet adnak a felhasználásra, reprodukálásra, módosításra. , módosíthatja, közzéteszi, lefordíthatja, származékos műveit hozza létre, terjesztheti és gyakorolja a szerzői jogokat és a nyilvánosságra vonatkozó jogokat a bejegyzésben szereplő anyagok tekintetében (beleértve a szöveget, képeket vagy videóanyagokat is) (a „Anyagok”) világszerte és / vagy az Anyagok más művekbe való beépítése bármely olyan médiába, amelyet most ismertek vagy később fejlesztettek ki az Anyagokban esetlegesen fennálló jogok teljes időtartama alatt. Az anyagnak a versenyre történő benyújtásával egy résztvevő:',
    '5a' => 'a. garantálja, hogy az Anyagok saját eredeti alkotása, és joga van a fentiekben meghatározott célok eléréséhez; hogy nem sérti valamelyik törvényt; hogy nem obszcén vagy buja; és nem sérti harmadik fél jogait;',
    '5b' => 'b. vállalja, hogy kártalanítja a támogatót a fenti jótállás megsértése miatt felmerülő valamennyi jogi költség, kártérítés és egyéb költség ellen;',
    '5c' => 'c. beleegyezik abba, hogy lemond minden olyan erkölcsi jogról, amelyet az Anyagok biztosítanak annak érdekében, hogy a pályázó eljusson a közzétételhez és a fentiekben meghatározott célokhoz.',
    '6' => '6. A promócióba való belépéskor minden résztvevő elismeri és egyetért azzal, hogy a promóter marketing anyagot küldhet a belépő által megadott e-mail címre. Minden ilyen e-mailben a belépőknek lehetőségük van arra, hogy lemondjanak a további e-mailekről.',
    'general' => 'Általános',
    '7' => '7. A támogató határozata és döntése minden ügyben végleges, és nem kerül sor promóciós levelezésre vagy megbeszélésre. A Támogató fenntartja magának a jogot, hogy ésszerű mérlegelési jogkörében: (a) kizárja bármely olyan kérelmezőt, versenytársat vagy jelöltet, akinek a magatartása ellentétes a szabályok szellemével vagy a promóció szándékával, és érvénytelenné nyilvánítja követeléseit vagy bejegyzéseit; ilyen magatartás alapján; b) semmilyen nyomtatási, termelési és / vagy forgalmazási hibából eredő követelések vagy bejegyzések érvénytelenné nyilvánítása (ideértve, de nem kizárólagosan a promóter bármely webhelyén jelentkező hibát, minden játékkártyát és / vagy más nyomtatott anyagot); vagy ha a promóció előkészítésének vagy lefolytatásának bármely aspektusában hiba történt, lényegesen befolyásolja a promóció eredményét vagy a kérelmezők számát vagy a követelések értékét; c) ésszerű értesítéssel kiegészíteni vagy lemondani minden szabályról; és / vagy (d) a promóció bármely résztvevőjének bármely olyan szakaszában történő visszavonása, amely a támogató ésszerű ellenőrzésén kívül eső körülmények között történik.',
    '8' => '8. Az ügynököktől vagy harmadik felektől nem fogadnak be ömlesztett bejegyzéseket.',
    '9' => '9. A törvény által megengedett legteljesebb mértékben (és az alábbi 14. bekezdéstől függően) a támogató kizárja a promócióval és / vagy a díjjal kapcsolatos minden garanciát, képviseletet, szövetséget és kötelezettséget (akár kifejezetten, akár hallgatólagosan).',
    '10' => '10. Ezekben a feltételekben semmi sem zárja ki a támogató felelősségét az alábbiakért: (i) gondatlanságából eredő halál vagy személyi sérülés; ii. csalás vagy csalárd félrevezetés; vagy (iii) a törvény által nem korlátozható vagy kizárt felelősség.',
    '11' => '11. A Támogató fenntartja magának a jogot, hogy saját belátása szerint módosítsa, felfüggessze vagy törölje a promóciót, amennyiben a vírus, a hibák, a bántalmazás, a csalás vagy más, a promóter ésszerő ellenőrzésén túlmutató ok sérti vagy akadályozza a promóció adminisztrációját, biztonságát vagy megfelelő játékát.',
    '12' => '12. Ha e feltételek bármelyike ​​érvénytelennek vagy teljes egészében vagy részben érvénytelennek minősül, akkor ezt a részt el kell különíteni a rendelkezések fennmaradó részétől, és a többi rendelkezés érvényességét és a szóban forgó rendelkezés fennmaradó részét nem lehet alkalmazni. érintettek.',
    '13' => '13. Ezeket a feltételeket Szlovákia törvényei szabályozzák, és minden vita a szlovák bíróságok kizárólagos hatáskörébe tartozik.',
    '14' => '14. A támogató a Šírava Park, s.r.o.',
    'past' => 'Korábbi nyertesek',

];