<?php

return [

    'title' => 'VŠEOBECNÉ OBCHODNÉ PODMIENKY A PRAVIDLÁ SÚŤAŽE O VÝHRU "POBYT PRE 2 OSOBY - ŠÍRAVA PARK"',
    'cond' => 'Podmienky:',
    '1' => '1. Táto výhra ("propagácia") je otvorená len pre obyvateľov EÚ, s výnimkou zamestnancov a zástupcov (a) organizátora alebo (b) akejkoľvek spoločnosti spojenej s výrobou alebo distribúciou tejto propagačnej akcie, ako aj ich príbuzných alebo ich rodinných príslušníkov alebo domácnosti.',
    '2' => '2. Súťaže sa môžu zúčastniť iba osoby staršie ako 18 rokov. Doklad totožnosti sa musí poskytnúť na požiadanie. Prihlásením do súťaže súťažiaci súhlasí so všetkými podmienkami a pravidlami tejto súťaže.',
    '3' => '3.  Súťaž sa začína o 11.00 h vo štvrtok 8. novembra 2018 a dátum konca súťaže je 4. novembra 2020 o 16:00 h ("Trvanie súťaže").',
    '4' => '4. Bude jeden víťaz, ktorý bude vybraný náhodným spôsobom od nezávislého sudcu zo všetkých vhodných vstupov, ktoré sa konajú prvý deň v mesiaci, každý mesiac od marca 2019 do novembra 2020. Víťazovi organizátor oznámi výhru e-mailovou formou alebo prostredníctvom správ na sociálnych médiách do jedného týždňa odo dňa konca súťaže spolu aj  s podmienkami, kde a ako si môže prevziať cenu. Ak sa víťaz do jedného týždňa neohlási a nedostaví pre výhru, organizátor následne znova vylosuje nezávislou osobou nového víťaza, ktorý bude kontaktovaný vyššie uvedenou formou.',
    '5' => '5. Súťažiaci súhlasia so spoluprácou a poskytnutím osobných údajov organizátorovi na účely spojené so súťažou ako sú reklamné účely, uverejnenie mena a fotografie víťaza na webových stránkach organizátora. Okrem toho, predložením prihlášky a vzhľadom na to, že organizátor udelil právo vstúpiť do propagačnej akcie, sa účastníci dohodnú, že poskytnú organizátorovi trvalé, bezplatné, nevýhradné právo na sublicenciu a licenciu na používanie, reprodukciu, úpravu , upravovať, publikovať, prekladať, vytvárať odvodené diela, distribuovať a vykonávať všetky autorské a reklamné práva vo vzťahu k akýmkoľvek materiálom obsiahnutým v položke (vrátane, nie však výhradne, textu, obrázkov alebo videozáznamov) (ďalej len "materiály") / alebo začleniť materiály do iných diel v akomkoľvek médiu, ktoré je v súčasnosti známe alebo neskôr vyvinuté na plné obdobie akýchkoľvek práv, ktoré môžu existovať v materiáloch. Odovzdaním materiálov do súťaže účastník:',
    '5a' => 'a. zaručuje, že materiály sú vlastnou originálnou prácou a že má právo sprístupniť ich na všetky vyššie uvedené účely; že neporušuje žiadne právo; že nie je obscénne alebo urážlivé; a že neporušuje práva akejkoľvek tretej strany;',
    '5b' => 'b. súhlasí s tým, že bude chrániť poskytovateľa proti všetkým právnym poplatkom, škodám a iným výdavkom, ktoré môžu vzniknúť v dôsledku porušenia vyššie uvedenej záruky;',
    '5c' => 'c. súhlasí s tým, že sa vzdáva akýchkoľvek morálnych práv v materiáloch na účely ich predloženia a uverejnenia zo strany organizátora a vyššie uvedených účelov.',
    '6' => '6. Prihlásením sa do súťaže každý účastník uznáva a súhlasí s tým, že organizátor môže poslať marketingový materiál na e-mailovú adresu poskytnutú účastníkom. Pri každom takomto e-maile majú účastníci možnosť odhlásiť sa od ďalších e-mailov.',
    'general' => 'Všeobecne',
    '7' => '7. Rozhodnutie organizátora o všetkých záležitostiach sú konečné a žiadna propagačná korešpondencia alebo diskusia nebude prípustná. Organizátor si vyhradzuje právo na základe vlastného uváženia: (a) diskvalifikovať každého žiadateľa, konkurenta alebo kandidáta, ktorého správanie je v rozpore s duchom pravidiel alebo úmyslom propagácie a vyhlásiť za neplatné niektoré alebo všetky ich nároky alebo vstupy založené na takomto správaní; (b) vyhlásiť za neplatné akékoľvek nároky alebo vstupy vyplývajúce z akýchkoľvek chýb pri tlači, výrobe a / alebo distribúcii (vrátane, ale bez obmedzenia na akékoľvek chyby na webových stránkach organizátora, akýchkoľvek herných kariet a / alebo iných tlačených materiálov) alebo ak došlo k chybe v akomkoľvek aspekte prípravy alebo vykonávania propagácie, ktorá podstatne ovplyvňuje výsledok propagácie alebo počet navrhovateľov alebo hodnotu nárokov; c) pridať alebo upustiť od akýchkoľvek pravidiel s primeraným oznámením; a / alebo (d) zrušenie propagácie alebo akejkoľvek jej časti v akomkoľvek štádiu v prípade okolností nad rámec primeranej kontroly organizátora.',
    '8' => '8. Nebudú akceptované žiadne hromadné položky, od agentov alebo tretích strán.',
    '9' => '9. V plnom rozsahu povolenom zákonom (s výhradou odseku 14 nižšie), organizátor vylučuje všetky záruky, vyjadrenia a záväzky (či už slovom alebo implicitne) týkajúce sa tejto súťaže a / alebo ceny.',
    '10' => '10. Žiadne ustanovenie týchto podmienok nebude vylučovať zodpovednosť organizátora za: (i) smrť alebo zranenie osôb v dôsledku nedbanlivosti; ii) podvod alebo podvodné skreslenie; alebo (iii) akýkoľvek záväzok, ktorý nemôže byť obmedzený alebo vylúčený zákonom.',
    '11' => '11. Organizátor si vyhradzuje právo na základe vlastného uváženia pozmeniť, pozastaviť alebo zrušiť súťaž v prípade vírusu, chyby, manipulácie, podvodu alebo inej príčiny mimo oprávnenej kontroly organizátora poškodzujú alebo bránia správe, bezpečnosti priebehu súťaže.',
    '12' => '12. Ak sa niektoré z ustanovení týchto podmienok považuje za neplatné alebo úplne nevymáhateľné, táto časť sa oddelí od ostatných ustanovení a platnosť ostatných ustanovení a zvyšok príslušného ustanovenia nebudú dotknuté.',
    '13' => '13. Tieto podmienky sa riadia zákonmi Slovenskej republiky a akýkoľvek spor bude podliehať výlučnej právomoci slovenských súdov.',
    '14' => '14. Organizátorom je Šírava Park, s.r.o.',
    'past' => 'Minulí víťazi',

];