<?php

return [

    'title' => 'WARUNKI DOTYCZĄCE NAGRODY NAGRÓD BEZPŁATNEJ WYGRAĆ" WYCIECZKA DLA 2 DO PARKU SIRAVA”',
    'cond' => 'Warunki wejścia',
    '1' => '1. Losowanie nagród ("Promocja") jest otwarte wyłącznie dla mieszkańców UE, z wyłączeniem pracowników i przedstawicieli (a) Organizatora lub (b) wszystkich firm związanych z produkcją lub dystrybucją tej Promocji, a także ich krewnych lub członków ich rodzina lub gospodarstwo domowe.',
    '2' => '2. Uczestnicy muszą mieć ukończone 18 lat w chwili wjazdu. Dowód kwalifikowalności musi być dostarczony na żądanie. Wchodząc w Promocję, uznajesz, że akceptujesz i jesteś związany niniejszymi warunkami.',
    '3' => '3. Promocja rozpocznie się o godzinie 11:00 czasu GMT w czwartek 8 listopada 2018 r., A czas zamknięcia / data promocji to 4:00 PM GMT w dniu 8 listopada 2020 r. ("Okres promocji").,',
    '4' => '4. Będzie jeden zwycięzca, który zostanie wylosowany losowo przez niezależnego sędziego ze wszystkich kwalifikujących się zgłoszeń, które odbyło się pierwszego dnia miesiąca, każdego miesiąca od marca 2019 do listopada 2020. Zwycięzca zostanie powiadomiony przez Organizatora przez e-mail lub poprzez bezpośrednie wiadomości w mediach społecznościowych, w tydzień od tej daty i otrzymają szczegółowe informacje o tym, jak przyjąć nagrodę. Niespełnienie przez zwycięzcę (zwycięzców) nagrody w sposób określony w ciągu tygodnia od e-maila Organizatora spowoduje, że jakiekolwiek roszczenie zostanie unieważnione, a Organizator następnie wybierze innego zwycięzcę (ponownie losowanego losowo w losowaniu) spośród wszystkich pozostałych kwalifikujących się zgłoszenia, z którymi skontaktujemy się jak wyżej.',
    '5' => '5. Uczestnicy wyrażają zgodę na rozsądną współpracę, aby umożliwić Organizatorowi wykorzystanie nazwy i / lub wizerunku zwycięzcy w celach reklamowych i promocyjnych w związku z niniejszą Promocją, w tym między innymi publikację imienia i nazwiska zwycięzcy oraz zdjęcia na stronach internetowych Organizatora. . Ponadto, przesyłając zgłoszenie i mając na uwadze promotora uprawniającego do przystąpienia do promocji, uczestnicy wyrażają zgodę na przyznanie Promotorowi stałego, wolnego od opłat, niewyłącznego, podlegającego podlicencjonowaniu prawa i licencji na użytkowanie, reprodukowanie, modyfikację , adaptować, publikować, tłumaczyć, tworzyć dzieł pochodnych, rozpowszechniać i wykonywać wszystkie prawa autorskie i reklamowe w odniesieniu do wszelkich materiałów zawartych we wpisie (w tym między innymi do tekstu, obrazów lub materiałów wideo) ("Materiały") na całym świecie i / lub włączenia Materiałów do innych prac w dowolnych mediach znanych lub opracowywanych przez cały okres obowiązywania wszelkich praw, które mogą istnieć w Materiałach. Przesyłając Materiały do ​​konkursu, uczestnik:',
    '5a' => 'a. gwarantuje, że Materiały są oryginalną pracą i że ma prawo udostępnić je we wszystkich wyżej wymienionych celach; że nie narusza żadnego prawa; że nie jest nieprzyzwoita ani zniesławiająca; oraz że nie narusza to praw żadnej strony trzeciej;',
    '5b' => 'b. zgadza się zabezpieczyć Organizatora przed wszelkimi opłatami prawnymi, odszkodowaniami i innymi kosztami, które mogą powstać w wyniku naruszenia powyższej gwarancji;',
    '5c' => 'c. wyraża zgodę na zrzeczenie się jakichkolwiek praw osobistych do Materiałów w celu ich przedłożenia i opublikowania przez Organizatora oraz w celach określonych powyżej.',
    '6' => '6. Przystępując do Promocji, każdy uczestnik przyjmuje do wiadomości i zgadza się, że Promotor może wysłać materiały marketingowe na adres e-mail podany przez uczestnika. Przy każdym takim e-mailu uczestnicy mają możliwość zrezygnowania z dalszych maili.',
    'general' => 'Ogólne',
    '7' => '7. Ustalenie i decyzja Promotora we wszystkich sprawach będzie ostateczna i nie będzie prowadzona żadna promocyjna korespondencja ani dyskusja. Organizator zastrzega sobie prawo według własnego uznania: (a) do zdyskwalifikowania dowolnego powoda, konkurenta lub kandydata, którego postępowanie jest sprzeczne z duchem zasad lub intencją awansu i uznanie za nieważne któregokolwiek lub wszystkie z ich roszczeń lub zgłoszeń w oparciu o takie zachowanie; (b) unieważnić wszelkie roszczenia lub zgłoszenia wynikające z błędów w druku, produkcji i / lub dystrybucji (w tym, ale nie wyłącznie, błędów na dowolnej stronie internetowej Organizatora, dowolnych kartach gier i / lub innych drukowanych materiałach) lub w przypadku błędu (błędów) w jakimkolwiek aspekcie przygotowania lub przeprowadzenia promocji, które mają istotny wpływ na wynik promocji lub liczbę powodów lub wartość roszczeń; (c) do dodania do lub zniesienia wszelkich zasad z odpowiednim wyprzedzeniem; i / lub (d) w celu anulowania promocji lub jakiejkolwiek jej części na dowolnym etapie w przypadku okoliczności pozostających poza uzasadnioną kontrolą Organizatora.',
    '8' => '8. Żadne zgłoszenia nie będą przyjmowane zbiorczo, od agentów lub stron trzecich.',
    '9' => '9. W najszerszym zakresie dozwolonym przez prawo (z zastrzeżeniem paragrafu 14 poniżej), Organizator niniejszym wyłącza wszelkie gwarancje, oświadczenia, zobowiązania i zobowiązania (wyraźne lub dorozumiane) związane z niniejszą Promocją i / lub nagrodą.',
    '10' => '10. Żadne z postanowień niniejszych warunków nie wyłącza odpowiedzialności Organizatora za: (i) śmierć lub uszkodzenie ciała w wyniku jego zaniedbania; (ii) oszustwo lub oszukańcze wprowadzenie w błąd; lub (iii) wszelką odpowiedzialność, której nie można ograniczyć lub wyłączyć z mocy prawa.',
    '11' => '11. Organizator zastrzega sobie prawo, według własnego uznania, do modyfikacji, zawieszenia lub anulowania Promocji w przypadku, gdy wirus, błędy, manipulacje, oszustwa lub inne przyczyny, poza uzasadnioną kontrolą Organizatora, będą miały wpływ na administrację, bezpieczeństwo lub właściwą grę Promocji.',
    '12' => '12. Jeżeli którekolwiek z postanowień niniejszych warunków zostanie uznane za nieważne lub niewykonalne w całości lub w części, część ta zostanie oddzielona od pozostałej części postanowień i ważność pozostałych postanowień, a pozostała część danego postanowienia nie będzie być pod wpływem.',
    '13' => '13. Niniejsze zasady i warunki podlegają prawu Słowacji, a wszelkie spory podlegają wyłącznej jurysdykcji sądów słowackich.',
    '14' => '14. Promotorem jest Šírava Park, s.r.o.',
    'past' => 'Wcześniejsi zwycięzcy',

];