<?php

return [

    'title' => 'ALGEMENE VOORWAARDEN VOOR GRATIS PRIJS TREKKEN OM TE WINNEN\' EEN REIS VOOR 2 NAAR SIRAVA PARK',
    'cond' => 'Voorwaarden voor toegang',
    '1' => '1. Deze prijstrekking (de "Promotie") staat alleen open voor EU-ingezetenen, met uitzondering van werknemers en agenten van (a) de Organisator of (b) elk bedrijf dat verbonden is met de productie of distributie van deze Promotie, evenals hun familieleden of leden van hun familie of huishouden.',
    '2' => '2. Deelnemers moeten 18 jaar of ouder zijn op het moment van deelname. Het bewijs van geschiktheid moet op verzoek worden verstrekt. Door deel te nemen aan de Promotie, wordt u geacht akkoord te gaan met en gebonden te zijn aan deze algemene voorwaarden.',
    '3' => '3. De promotie start om 11.00 uur CET op donderdag 8 november 2018 en de sluitingstijd / -datum voor de actie is 16.00 uur GMT op 8 november 2020 (promotieperiode \').',
    '4' => '4. Er zal één winnaar zijn die in een willekeurige trekking wordt geselecteerd door een onafhankelijke rechter uit alle in aanmerking komende inzendingen, gehouden op de eerste dag van de maand, elke maand van maart 2019 tot november 2020. De winnaar (s) worden op de hoogte gebracht door de organisator per e-mail of via direct messaging op sociale media, binnen een week na deze datum en zullen details worden gegeven over hoe ze hun prijs kunnen accepteren. Als de winnaar (s) de prijs niet accepteren op de aangegeven manier binnen één week na de e-mail van de organisator, zal elke claim ongeldig worden verklaard en de promotor zal vervolgens een andere winnaar selecteren (opnieuw willekeurig geselecteerd bij een gelijkspel) van alle resterende in aanmerking komende winnaars. inzendingen die zullen worden gecontacteerd zoals hierboven.',
    '5' => '5. Deelnemers komen overeen om redelijke medewerking te verlenen om de Organisator in staat te stellen de naam en / of gelijkenis van de winnaar te gebruiken voor reclame- en publiciteitsdoeleinden in verband met deze Promotie, inclusief maar niet beperkt tot publicatie van de naam van de winnaar en foto op de websites van de Promotor . Door een inzending in te dienen en rekening houdend met de organisator die het recht verleent om deel te nemen aan de actie, komen de deelnemers bovendien overeen de promotor een eeuwigdurend, royaltyvrij, niet-exclusief sublicentieerbaar recht en licentie te verlenen voor gebruik, reproductie, wijziging , aanpassen, publiceren, vertalen, afgeleide werken maken van, distribueren en uitoefenen van alle auteursrechten en publiciteitsrechten met betrekking tot alle materialen die zijn opgenomen in de vermelding (inclusief maar niet beperkt tot tekst, afbeeldingen of videomateriaal) (de "Materialen") wereldwijd en / of om de Materialen in andere werken op te nemen in elk medium dat nu bekend is of later is ontwikkeld voor de volledige duur van alle rechten die in de Materialen kunnen bestaan. Door materialen in te sturen bij de wedstrijd, een deelnemer:',
    '5a' => 'a. garandeert dat het Materiaal zijn eigen originele werk is en dat het het recht heeft om het beschikbaar te maken voor alle bovengenoemde doeleinden; dat het geen enkele wet overtreedt; dat het niet obsceen of lasterlijk is; en dat het de rechten van een derde partij niet schendt;',
    '5b' => 'b. stemt ermee in de organisator schadeloos te stellen voor alle juridische kosten, schade en andere kosten die mogelijk zijn ontstaan ​​als gevolg van een schending van de bovenstaande garantie;',
    '5c' => 'c. stemt ermee in afstand te doen van alle morele rechten in de Materialen met het oog op de indiening en publicatie ervan door de Organisator en de hierboven gespecificeerde doeleinden.',
    '6' => '6. Door deel te nemen aan de Promotie, erkent en stemt elke deelnemer ermee in dat de Promotor marketingmateriaal naar het door de deelnemer opgegeven e-mailadres kan sturen. Op elk van deze e-mail hebben nieuwkomers de mogelijkheid om zich uit te schrijven voor verdere e-mails.',
    'general' => 'Algemeen',
    '7' => '7. De vaststelling en beslissing van de Organisator over alle zaken is definitief en er zal geen promotiecorrespondentie of discussie worden gevoerd. De organisator behoudt zich het recht voor naar eigen goeddunken: (a) om een ​​eiser, concurrent of kandidaat te diskwalificeren wiens gedrag in strijd is met de geest van de regels of de intentie van de promotie en om alle of alle claims of vermeldingen ongeldig of nietig te verklaren op basis van dergelijk gedrag; (b) om claims of ingangen als gevolg van druk-, productie- en / of distributiefouten (inclusief maar niet beperkt tot fouten op een website van de Organisator, speelkaarten en / of andere gedrukte materialen) als ongeldig te verklaren of wanneer er fouten zijn (zijn) in welk aspect van de voorbereiding of het verloop van de promotie dan ook die van invloed zijn op het resultaat van de promotie of het aantal eisers of de waarde van claims; (c) om toe te voegen aan of afstand te doen van regels op redelijke kennisgeving; en / of (d) om de promotie of een deel ervan in elk stadium te annuleren in geval van omstandigheden buiten de redelijke controle van de Organisator.',
    '8' => '8. Er worden geen inzendingen in bulk geaccepteerd, van agenten of van derden.',
    '9' => '9. Voor zover toegestaan ​​door de wet (en behoudens paragraaf 14 hieronder) sluit de organisator hierbij alle garanties, verklaringen, convenanten en aansprakelijkheden (expliciet of impliciet) met betrekking tot deze actie en / of de prijs uit.',
    '10' => '10. Niets in deze algemene voorwaarden zal de aansprakelijkheid van de organisator uitsluiten voor: (i) overlijden of persoonlijk letsel als gevolg van zijn nalatigheid; (ii) fraude of frauduleuze verkeerde voorstelling van zaken; of (iii) elke aansprakelijkheid die niet wettelijk kan worden beperkt of uitgesloten.',
    '11' => '11. De Organisator behoudt zich het recht voor om naar eigen goeddunken de Promotie te wijzigen, op te schorten of te annuleren indien virussen, bugs, knoeien, fraude of andere oorzaken buiten de redelijke controle van de Organisator de administratie, veiligheid of correct spel van de Promotie corrupt maken of hinderen. ',
    '12' => '12. Als een van de bepalingen van deze algemene voorwaarden geheel of gedeeltelijk ongeldig of niet-afdwingbaar wordt verklaard, wordt dat deel gescheiden van de rest van de bepalingen en de geldigheid van de andere bepalingen en de rest van de bepaling in kwestie wordt niet worden beïnvloed.',
    '13' => '13. Deze algemene voorwaarden worden beheerst door het recht van Slowakije en elk geschil is onderworpen aan de exclusieve jurisdictie van de Slowaakse rechtbanken.',
    '14' => '14. De organisator is Šírava Park, s.r.o.',
    'past' => 'Vorige winnaars',

];