<?php

return [

    'title' => 'TEILNAHMEBEDINGUNGEN FÜR DEN KOSTENLOSEN PREISZIEL ZUM GEWINNEN "EINE REISE FÜR 2 ZUM SIRAVA-PARK"',
    'cond' => 'Einreisebestimmungen',
    '1' => '1. Diese Verlosung (die "Promotion") steht nur EU-Gebietsansässigen offen, ausgenommen sind Mitarbeiter und Vertreter von (a) dem Promoter oder (b) Unternehmen, die mit der Produktion oder dem Vertrieb dieser Promotion in Verbindung stehen, sowie deren Angehörigen oder Mitgliedern von ihre Familie oder Haushalt.',
    '2' => '2. Die Teilnehmer müssen zum Zeitpunkt der Einreise mindestens 18 Jahre alt sein. Der Nachweis der Berechtigung ist auf Anfrage vorzulegen. Durch die Teilnahme an der Aktion akzeptieren Sie diese Bedingungen und sind an diese gebunden.',
    '3' => '3. Die Promotion beginnt am Donnerstag, dem 8. November 2018, um 11:00 Uhr GMT, und der Schließungszeitpunkt der Promotion ist am 8. November 2020 um 16:00 Uhr (Promotionszeitraum).',
    '4' => '4. Es wird einen Gewinner geben, der durch einen unabhängigen Richter aus allen teilnahmeberechtigten Einsätzen am Rand eines Monats vom März 2019 bis November 2020 jeden Monat zufällig ausgewählt wird. Der / die Gewinner werden vom Veranstalter per E-Mail oder durch direkte Benachrichtigung in den sozialen Medien benachrichtigt eine Woche von diesem Datum und wird Details darüber erhalten, wie sie ihren Preis annehmen können. Wenn der / die Gewinner / innen den Gewinn nicht innerhalb einer Woche nach der E-Mail des Veranstalters in der angegebenen Weise annimmt, wird der Anspruch ungültig. Der Veranstalter wählt dann einen anderen Gewinner (erneut zufällig in einer Ziehung ausgewählt) aus allen verbleibenden Teilnehmern aus Einträge, die wie oben beschrieben kontaktiert werden.',
    '5' => '5. Die Teilnehmer erklären sich damit einverstanden, eine angemessene Zusammenarbeit anzubieten, damit der Veranstalter den Namen und / oder das Bild des Gewinners zu Werbe- und Werbezwecken im Zusammenhang mit dieser Aktion verwenden kann, einschließlich der Veröffentlichung des Namens des Gewinners und des Fotos auf den Websites des Veranstalters . Durch die Einsendung eines Beitrags und unter Berücksichtigung des Veranstalters, der ein Recht zur Teilnahme an der Aktion einräumt, erklären sich die Teilnehmer damit einverstanden, dem Veranstalter ein unbefristetes, gebührenfreies, nicht ausschließliches, unterlizenzierbares Recht und eine Lizenz zur Verwendung, Reproduktion und Änderung zu gewähren Sie müssen alle Urheber- und Publizitätsrechte in Bezug auf jegliches in dem Beitrag enthaltene Material (einschließlich, jedoch nicht beschränkt auf Text, Bilder oder Videomaterial) (das „Material“) weltweit und anpassen, veröffentlichen, übersetzen, abgeleitete Werke erstellen, verteilen und ausüben / oder um die Materialien in andere Werke in Medien einzubringen, die jetzt bekannt sind oder später für die gesamte Laufzeit der eventuell in den Materialien bestehenden Rechte entwickelt werden. Durch die Einreichung von Materialien für den Wettbewerb kann ein Teilnehmer:',
    '5a' => 'a. sichert zu, dass das Material ein eigenes Originalwerk ist und es berechtigt ist, sie für alle oben genannten Zwecke zur Verfügung zu stellen; dass es kein Gesetz verletzt; dass es nicht obszön oder beleidigend ist; und dass es nicht die Rechte Dritter verletzt;',
    '5b' => 'b. erklärt sich einverstanden, den Veranstalter von allen gesetzlichen Gebühren, Schäden und anderen Kosten zu entschädigen, die infolge eines Verstoßes gegen die vorstehende Garantie entstehen können;',
    '5c' => 'c. erklärt sich damit einverstanden, auf die Urheberpersönlichkeitsrechte in den Materialien zum Zwecke der Einreichung und Veröffentlichung durch den Veranstalter und der oben genannten Zwecke zu verzichten.',
    '6' => '6. Mit der Teilnahme an der Aktion erkennt jeder Teilnehmer an und stimmt zu, dass der Veranstalter Werbematerial an die vom Teilnehmer angegebene E-Mail-Adresse senden darf. In jeder dieser E-Mails haben die Teilnehmer die Möglichkeit, sich von weiteren E-Mails abzumelden.',
    'general' => 'General',
    '7' => '7. Die Feststellung und Entscheidung des Veranstalters in allen Angelegenheiten ist endgültig und es wird keine Werbekorrespondenz oder Diskussion geführt. Der Veranstalter behält sich das Recht vor, nach seinem vernünftigen Ermessen: (a) jeden Antragsteller, Wettbewerber oder Nominee, dessen Verhalten gegen den Geist der Regeln oder die Absicht der Werbeaktion verstößt, zu disqualifizieren und alle oder alle seine Ansprüche oder Beiträge für nichtig zu erklären basierend auf einem solchen Verhalten; (b) alle Ansprüche oder Eingaben, die aus Druck-, Produktions- und / oder Vertriebsfehlern resultieren, für ungültig zu erklären (einschließlich, jedoch nicht beschränkt auf Fehler auf einer Website des Veranstalters, Spielkarten und / oder anderen gedruckten Materialien). oder wenn bei irgendeinem Aspekt der Vorbereitung oder Durchführung der Werbeaktion ein oder mehrere Fehler aufgetreten sind, die das Ergebnis der Werbeaktion oder die Anzahl der Antragsteller oder den Wert der Ansprüche wesentlich beeinflussen; (c) um Regeln mit angemessener Frist zu ergänzen oder auf diese zu verzichten; und / oder (d) die Promotion oder Teile davon zu einem beliebigen Zeitpunkt zu annullieren, wenn Umstände außerhalb des Einflussbereichs des Veranstalters liegen.',
    '8' => '8. Es werden keine Einsendungen von Agenten oder Dritten in Massen angenommen.',
    '9' => '9. Der Veranstalter schließt hiermit, soweit dies gesetzlich zulässig ist (und vorbehaltlich des nachstehenden Absatzes 14), alle Garantien, Zusicherungen, Verpflichtungen und Haftungen (ob ausdrücklich oder stillschweigend), die sich auf diese Aktion und / oder den Preis beziehen, aus.',
    '10' => '10. Nichts in diesen Geschäftsbedingungen schließt die Haftung des Veranstalters aus für: (i) Tod oder Körperverletzung als Folge seiner Fahrlässigkeit; (ii) Betrug oder betrügerische Falschdarstellung; oder (iii) eine Haftung, die vom Gesetz nicht eingeschränkt oder ausgeschlossen werden kann.',
    '11' => '11. Der Veranstalter behält sich das Recht vor, die Werbeaktion nach seinem alleinigen Ermessen zu ändern, auszusetzen oder zu annullieren, falls Viren, Fehler, Manipulationen, Betrug oder andere Gründe außerhalb des Einflussbereichs des Veranstalters die Verwaltung, Sicherheit oder das ordnungsgemäße Spielen der Werbeaktion beeinträchtigen oder behindern.',
    '12' => '12. Sollte eine der Bestimmungen dieser Bedingungen ganz oder teilweise unwirksam oder undurchsetzbar sein, wird dieser Teil von den übrigen Bestimmungen abgetrennt. Die Gültigkeit der übrigen Bestimmungen und der Rest der betreffenden Bestimmung ist nicht zulässig betroffen sein.',
    '13' => '13. Diese Bedingungen unterliegen den Gesetzen der Slowakei, und alle Streitigkeiten unterliegen der ausschließlichen Zuständigkeit der slowakischen Gerichte.',
    '14' => '14. Der Veranstalter ist die Šírava Park, s.r.o.',
    'past' => 'Vergangene Gewinner',

];